export function formatHelp(): string {
  return [
    'agent-plugins (apg) — LLM skills manager & sync',
    '',
    'Usage:',
    '  apg skills <add|rm|update|manage|sync|collect|list> [args] [--options]',
    '  agent-plugins skills ... (same as apg)',
    '',
    'Abbreviations:',
    '  skills=s, add=a, rm=rm, update=up, manage=m, sync=sy, collect=c, list=ls',
    '',
    'Examples:',
    '  apg skills add <git-url|local-path>',
    '  apg skills sync --target codex --scope global',
    '  apg s ls',
    '',
    'Options:',
    '  -h, --help       Show help',
    '  -V, --version    Show version',
    '  -d, --dry-run    Preview changes',
    '  -f, --force      Overwrite on conflicts',
    '  -t, --target     Sync/collect target (cursor|gemini|codex|claude-code|antigravity)',
    '  -g, --scope      global',
    '  -l, --scope      local (default)',
    '  -C, --cwd <dir>  Override project cwd for local scope',
    '',
    'Environment:',
    '  APG_HOME / AGENT_PLUGINS_HOME  Override ~/.agent-plugins (useful for testing)',
    '',
  ].join('\n');
}
